[platformio]
default_envs = esp32c3

[env]
test_framework = unity

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
  -std=gnu++17
build_unflags =
  -std=gnu++11

[env:native]
platform = native
build_flags =
  -std=c++17
  -Iinclude
  -Isrc
build_src_filter =
  +<serial_bridge.cpp>
  +<reset_control.cpp>
