#pragma once

#define NANOBMC_NAME "NanoBMC"
#define NANOBMC_VERSION "0.1.0"

#define WIFI_AP_SSID "NanoBMC"
#define WIFI_AP_PASSWORD "changeme-nanobmc"

#define SERIAL_BAUD 115200
#define SERIAL_RX_GPIO 0
#define SERIAL_TX_GPIO 1
#define SERIAL_TCP_PORT 23

#define PI_RESET_GPIO 4
#define PI_RESET_ACTIVE_LOW false
#define PI_RESET_PULSE_MS 500

#define NANOBMC_IDLE_POWER_SAVE_ENABLED true
#define NANOBMC_IDLE_DELAY_MS 25
#define NANOBMC_ACTIVE_DELAY_MS 1
#define NANOBMC_IDLE_LIGHT_SLEEP_ENABLED false
#define NANOBMC_IDLE_LIGHT_SLEEP_MS 25
#define NANOBMC_WEB_REQUEST_IDLE_GRACE_MS 100
